//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTBlockersStuff.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTBlockersStuff.Language.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ColorSelectionButtonTextCancel {
            get {
                return ResourceManager.GetString("ColorSelectionButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string ColorSelectionButtonTextOk {
            get {
                return ResourceManager.GetString("ColorSelectionButtonTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Selection (WIP) ähnelt.
        /// </summary>
        internal static string ColorSelectionTitle {
            get {
                return ResourceManager.GetString("ColorSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amber ähnelt.
        /// </summary>
        internal static string GatheringSpotTitleAmber {
            get {
                return ResourceManager.GetString("GatheringSpotTitleAmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cobalt ähnelt.
        /// </summary>
        internal static string GatheringSpotTitleCobalt {
            get {
                return ResourceManager.GetString("GatheringSpotTitleCobalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crimson ähnelt.
        /// </summary>
        internal static string GatheringSpotTitleCrimson {
            get {
                return ResourceManager.GetString("GatheringSpotTitleCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gathering ähnelt.
        /// </summary>
        internal static string GatheringspotTitleMain {
            get {
                return ResourceManager.GetString("GatheringspotTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eggs bar color. ähnelt.
        /// </summary>
        internal static string SettingColorSelectionEggsText {
            get {
                return ResourceManager.GetString("SettingColorSelectionEggsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color for the eggs bar. ähnelt.
        /// </summary>
        internal static string SettingColorSelectionEggsTooltipText {
            get {
                return ResourceManager.GetString("SettingColorSelectionEggsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Husks bar color. ähnelt.
        /// </summary>
        internal static string SettingColorSelectionHusksText {
            get {
                return ResourceManager.GetString("SettingColorSelectionHusksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color for the husks bar. ähnelt.
        /// </summary>
        internal static string SettingColorSelectionHusksTooltipText {
            get {
                return ResourceManager.GetString("SettingColorSelectionHusksTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eggs ähnelt.
        /// </summary>
        internal static string TimerBarTextEggs {
            get {
                return ResourceManager.GetString("TimerBarTextEggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Husks ähnelt.
        /// </summary>
        internal static string TimerBarTextHusks {
            get {
                return ResourceManager.GetString("TimerBarTextHusks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ready ähnelt.
        /// </summary>
        internal static string TimerBarTextReady {
            get {
                return ResourceManager.GetString("TimerBarTextReady", resourceCulture);
            }
        }
    }
}
